# Generated by Django 4.2.1 on 2024-04-01 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_alter_product_serial_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='serial_number',
        ),
    ]
