# Generated by Django 4.2.1 on 2024-04-01 18:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_remove_product_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='serial_number',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
